Feature/docker workflow
AbandonTech/RecipleaseAPI pull request #13
Opened 2022-04-14 20:12 UTC by GDWR

Does what it says on the tin, remove https as it won't be needed and reduces the complexity of deployment by 1000x

2022-04-20 00:31 UTC, fisher60 commented on Dockerfile
>  EXPOSE 443
Will these be configurable when building/starting the container? If we are running this on my server, it will need to be configured to run on a custom port.

I am also curious if we know how this is running in the container? Apache? Nginx? I looked around and could not find much info on the base image.

2022-04-20 09:32 UTC, GDWR commented on Dockerfile
>  EXPOSE 443
This is just exposing them to the docker network. 
This has nothing to do with the user configuration, as that is down to the user.

2022-04-20 09:32 UTC, GDWR commented on Dockerfile
>  EXPOSE 443
You can bind any port you want when configuring your deployment

2022-04-20 09:34 UTC, GDWR commented on Dockerfile
>  EXPOSE 443
https://hub.docker.com/_/microsoft-dotnet-framework-aspnet/
IIS 10

2022-04-20 09:36 UTC, GDWR commented on Dockerfile
>  EXPOSE 443
> The EXPOSE instruction does not actually publish the port. It functions as a type of documentation between the person who builds the image and the person who runs the container, about which ports are intended to be published. To actually publish the port when running the container, use the -p flag on docker run to publish and map one or more ports, or the -P flag to publish all exposed ports and map them to high-order ports.

https://docs.docker.com/engine/reference/builder/#expose

2022-04-20 17:11 UTC, fisher60 requested changes
I believe 443 should be removed, but not certain about this change.

2022-04-20 17:11 UTC, fisher60 commented on Dockerfile
>  EXPOSE 443
I assume port 443 be removed since we are not handling https anymore.

2022-04-20 18:07 UTC, GDWR commented on Dockerfile
>  EXPOSE 443
You are correct, good spot

2022-04-20 18:09 UTC, GDWR commented on Dockerfile
>  EXPOSE 443
Updated

2022-04-21 02:45 UTC, fisher60 approved these changes
LGTM

2022-04-21 08:15 UTC, merged