Feature/create crud endpoints
AbandonTech/RecipleaseAPI pull request #6
Opened 2022-03-20 17:10 UTC by GDWR

2022-03-20 17:54 UTC, fisher60 requested changes
Looks good and is fully functioning. I think some minor tweaks should be made before merging, as well as some considerations in my comments below.

2022-03-20 17:54 UTC, fisher60 commented on Controllers/RecipeController.cs
> +    /// If a recipe with that id does not exists, a 404 response will be returned.
The 404 responses are not documented in the swagger, I am unsure if there is an easy fix for this.

2022-03-20 17:54 UTC, fisher60 commented on Controllers/RecipeController.cs
> -    [HttpGet(Name = "GetRecipes")]
We probably do want to keep the name on this one. The current endpoint at `/recipe` is misleading. I would expect it to be `recipes` or `allRecipes`

2022-03-20 17:54 UTC, fisher60 commented on Controllers/RecipeController.cs
> +        };
We will need to be able to specify the relations of ingredients before any endpoints creating or modifying recipes are fully functional. Do we want to add that logic to this PR as well?

2022-03-20 17:54 UTC, fisher60 commented on Controllers/RecipeController.cs
> +            return StatusCode(500);
Is the 500 code accurate here? 400 might be more accurate? Unless this exception is just to catch if a client makes a valid request, the server failed for unknown reasons, and the client can/should repeat the same request.

2022-03-20 17:54 UTC, fisher60 commented on Controllers/RecipeController.cs
> +        return Ok();
I would prefer to receive a message confirming the action along with the 200 response for deleting.

2022-03-20 17:54 UTC, fisher60 commented on Controllers/RecipeController.cs
> +            return CreateRecipe(new CreateRecipeDto {Name = recipe.Name, Servings = recipe.Servings});
We may want to get fancy and return a HTTP 201 in this case?

2022-03-20 17:54 UTC, fisher60 commented on Models/Recipe.cs
> +public class CreateRecipeDto
PR is missing migrations for this database change.

2022-03-20 17:56 UTC, GDWR commented on Models/Recipe.cs
> +public class CreateRecipeDto
It will not be included in the database. A Dto (DataTransferObject)'s only goal is to be a structure of data to be sent from and sent to the API. 

The reason I did it for this case, is because we will not want users to specify an ID when creating new Recipe.

2022-03-20 17:57 UTC, GDWR commented on Controllers/RecipeController.cs
> +            return CreateRecipe(new CreateRecipeDto {Name = recipe.Name, Servings = recipe.Servings});
Very good call, [201 Created](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/201). I will look into adding this.

2022-03-20 17:58 UTC, GDWR commented on Controllers/RecipeController.cs
> +        return Ok();
I'm unsure of what you mean by this, just return "recipe of {id} has been deleted"? I don't see any value in this.

2022-03-20 17:59 UTC, GDWR commented on Controllers/RecipeController.cs
> +            return StatusCode(500);
The 500 is because we are having an error that we haven't accounted for. 400 would be if it is specifically an error on the input/user part.

2022-03-20 18:13 UTC, GDWR commented on Controllers/RecipeController.cs
> +            return CreateRecipe(new CreateRecipeDto {Name = recipe.Name, Servings = recipe.Servings});
Should this also be done for `CreateRecipe` endpoint?

2022-03-20 18:17 UTC, GDWR commented on Controllers/RecipeController.cs
> +        };
No, that would be seperate. This is basic CRUD for `recipe`

2022-03-20 18:19 UTC, GDWR commented on Controllers/RecipeController.cs
> -    [HttpGet(Name = "GetRecipes")]
changed to be at `api/recipe/all`. 

Using `Name = "recipes"` doesn't seem to change the endpoint name. I prefer this too.

2022-03-20 18:48 UTC, GDWR commented on Controllers/RecipeController.cs
> +    /// If a recipe with that id does not exists, a 404 response will be returned.
Added in docstrings. This is a good place to look at for what you can do [aspnetcore swashbuckler](https://docs.microsoft.com/en-us/samples/aspnet/aspnetcore.docs/getstarted-swashbuckle-aspnetcore/?tabs=visual-studio) 

Do be wary that this is old ASP 2.2, so some of the attribute as not required as it is infered from the docstrings.

2022-03-22 18:15 UTC, fisher60 commented on Controllers/RecipeController.cs
> +        return Ok();
Yes, I see now that we are returning a 404 if it does not exist, that should be plenty explicit.

2022-03-22 18:20 UTC, fisher60 commented on Controllers/RecipeController.cs
> +            return CreateRecipe(new CreateRecipeDto {Name = recipe.Name, Servings = recipe.Servings});
I would expect a 201 any time an entry is created.

2022-03-22 18:22 UTC, fisher60 requested changes
Fix broken endpoint

2022-03-22 18:22 UTC, fisher60 commented on Controllers/RecipeController.cs
> +    public ActionResult<Recipe> CreateRecipe(CreateRecipeDto recipe)
This enpoint returns a 400 error on a valid request.

2022-03-22 18:27 UTC, fisher60 approved these changes
LGTM

2022-03-22 18:35 UTC, merged