Add Users and JWT auth
AbandonTech/RecipleaseAPI pull request #9
Opened 2022-04-01 22:05 UTC by fisher60

2022-04-02 11:15 UTC, GDWR requested changes
Please update the `README.md` with the new required env vars and where to put them, i.e. `launchSettings.json`. Please also just create empty values in there to make it easier to spot.

additionally, I am unable to get the database to "update" as I get an error.
```
PS R:\AbandonTech\Reciplease> dotnet ef database update
Build started...
Build succeeded.
System.ArgumentNullException: Google OAuth Client Id cannot be null. (Parameter 'googleClientId')
   at Reciplease.RecipleaseContext..ctor(DbContextOptions`1 options) in R:\AbandonTech\Reciplease\Contexts\RecipleaseContext.cs:line 27
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType
)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetServiceOrCreateInstance(IServiceProvider provider, Type type)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass21_3.<FindContextTypes>b__11()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Google OAuth Client Id cannot be null. (Parameter 'googleClientId')
```

Please provide documentation on how to get the database to match what EF requires so I can run this branch.

2022-04-03 13:39 UTC, GDWR requested changes
## Changes

See code review threads and headings below.

### Endpoint to test authorized attribute

Can you make an `Authorized` endpoint that will retrieve some information about your account? For now, a GET method called `Profile` that will return your Username & Email.

### Empty file

`Models/User.cs` is an empty file, remove it.

## Future Notes 

### Error responses
A future issue/pr will have to deal with correctly returning errors to the user, as short passwords give a 500 response.
```
warn: Microsoft.AspNetCore.Identity.UserManager[14]
      User password validation failed: PasswordTooShort;PasswordRequiresNonAlphanumeric;PasswordRequiresDigit;PasswordRequiresUpper.
```
### Missing XML Docstrings

We are missing XML Docstrings for the endpoints, this can be deferred to a future PR/Issue so we can complete issues at the same time.

2022-04-03 13:39 UTC, GDWR commented on Contexts/RecipleaseContext.cs
>          var path = System.IO.Path.Join(CurrentDirectory, "TempData");
We can use dependency injection to inject the config. Example below for one of the env vars.

```csharp
    private readonly string? _googleClientId;
    
    public RecipleaseContext(DbContextOptions<RecipleaseContext> options, IConfiguration configuration) : base(options)
    {
          googleClientId = configuration["GOOGLE_OAUTH_CLIENT_ID"];
          ... // Other constructor stuff.
    }
```
If we can use `private` and `readonly` as they should only be accessed in this class and set in the contructor.

2022-04-03 13:39 UTC, GDWR commented on Controllers/UserController.cs
> +    }
Find somewhere better to situate this class, I'd recommend in `Models` and a rename to `AuthenticateRequestDto`.

2022-04-03 13:39 UTC, GDWR commented on Controllers/UserController.cs
> +        return Ok( payload );
```suggestion
        var settings = new GoogleJsonWebSignature.ValidationSettings();
        
        settings.Audience = new List<string> { _context.googleClientId };

        var payload = GoogleJsonWebSignature.ValidateAsync(data.IdToken, settings).Result;
        return Ok( payload );
```

2022-04-03 13:39 UTC, GDWR commented on Controllers/UserController.cs
> +        if (user != null && await _userManager.CheckPasswordAsync(user, model.Password))
Can this be a return early? to reduce nesting.

2022-04-03 13:39 UTC, GDWR commented on Controllers/UserController.cs
> +            };
I'm not fully sure about how this works, but I would expect an `email` or something like that to be on here?

Or would that still be accessible in other endpoints, regardless if it is added here?

2022-04-03 13:39 UTC, GDWR commented on Program.cs
> +
indentation looks off.
```suggestion
    {
        var clientId = Environment.GetEnvironmentVariable("GOOGLE_OAUTH_CLIENT_ID");
        var clientSecret = Environment.GetEnvironmentVariable("GOOGLE_OAUTH_CLIENT_SECRET");

        if (clientId == null)
            throw new ArgumentNullException(nameof(clientId), "Google OAuth Client Id cannot be null.");
        if (clientSecret == null) 
            throw new ArgumentNullException(nameof(clientSecret), "Google OAuth Client Secret cannot be null.");
    
        googleOptions.ClientId = clientId;
        googleOptions.ClientSecret = clientSecret;
    });

```

2022-04-03 13:39 UTC, GDWR commented on Properties/launchSettings.json
> +        "ValidIssuer": "",
We can assume empty Env vars are incorrect for these values, can we add this to where we are checking for `null` so it fails quicker.

2022-04-03 19:11 UTC, fisher60 commented on Contexts/RecipleaseContext.cs
>          var path = System.IO.Path.Join(CurrentDirectory, "TempData");
Yes, we should add this to a future refactor in my opinion.

2022-04-03 20:04 UTC, fisher60 commented on Controllers/UserController.cs
> +            };
The current setup could allow user data to be retrieved via username at the `profile` endpoint if needed, however we should not have the need to get user data from the JWT. The JWT should pass user roles in the token, no DB queries should need to be made when using or validating a JWT.

2022-04-03 20:24 UTC, GDWR requested changes
The profile endpoint you have made doesn't test/use the auth you have made. Please make it do so.

2022-04-03 20:24 UTC, GDWR commented on Controllers/AuthController.cs
> +            return Unauthorized();
un reachable code?

2022-04-03 20:24 UTC, GDWR commented on Controllers/UserController.cs
> +    public async Task<ActionResult<UserDto>> Profile([FromQuery] UserInputDto user)
This should be an `[Authorized]` endpoint, where the correct profile is gathered from the JWT as that is how we authorize them.

2022-04-03 20:28 UTC, GDWR commented on Contexts/RecipleaseContext.cs
>          var path = System.IO.Path.Join(CurrentDirectory, "TempData");
Please make a chasing issue for this, after merge.

2022-04-04 02:43 UTC, fisher60 commented on Controllers/UserController.cs
> +    public async Task<ActionResult<UserDto>> Profile([FromQuery] UserInputDto user)
All user endpoints are currently authorized, the register endpoint is set to explicitly allow unauthorized. So the profile endpoint is authorized by default.

2022-04-04 02:44 UTC, fisher60 commented on Controllers/AuthController.cs
> +            return Unauthorized();
Oops, remnant of the old method.

2022-04-10 16:59 UTC, GDWR approved these changes

2022-04-10 17:00 UTC, merged

2022-04-10 17:00 UTC, GDWR commented
@fisher60 Please create the new Issues mentioned across this ticket. Link them here too for accessibility.

2022-04-11 14:43 UTC, fisher60 commented
issues #10, #11, and #12 have been created as a result of the work here.